# Generated by Django 6.0.2 on 2026-03-03 19:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Bounding box or extent of the project', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.BooleanField(default=True)),
                ('z_index', models.IntegerField(default=0, help_text='Layer stacking order (higher = on top)')),
                ('style_config', models.JSONField(blank=True, default=dict, help_text='MapLibre GL style configuration for this layer')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata/properties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='data.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Layers',
                'ordering': ['z_index', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization'], name='projects_pr_organiz_da3a59_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by'], name='projects_pr_created_c24ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['project', 'z_index'], name='projects_la_project_f1cfea_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['datasource'], name='projects_la_datasou_4476d3_idx'),
        ),
    ]
