# Generated by Django 6.0.2 on 2026-03-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('datasource_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster'), ('pmtiles', 'PMTiles'), ('mvt', 'Mapbox Vector Tiles')], max_length=20)),
                ('storage_url', models.CharField(help_text='URL or path to data source (GeoJSON, GeoTIFF, PMTiles, etc.)', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Data source metadata: projection, geometry_type, attributes, etc.')),
                ('is_public', models.BooleanField(default=False, help_text='Accessible to all org members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasources', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Datasources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='data_dataso_organiz_4492ad_idx'), models.Index(fields=['datasource_type'], name='data_dataso_datasou_805179_idx'), models.Index(fields=['created_by'], name='data_dataso_created_d9c5dc_idx')],
            },
        ),
    ]
