# Generated by Django 6.0.2 on 2026-03-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('organization', 'Organization'), ('project', 'Project'), ('datasource', 'Datasource')], max_length=50)),
                ('resource_id', models.IntegerField(help_text='ID of the resource (org_id, project_id, etc.)')),
                ('role', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('manage', 'Manage')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('subject_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_permissions', to='organizations.team')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perm_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='permissions_resourc_147443_idx'), models.Index(fields=['subject_user', 'role'], name='permissions_subject_481516_idx'), models.Index(fields=['subject_team', 'role'], name='permissions_subject_a7a0c4_idx')],
            },
        ),
    ]
